services:
  meeting-calendar-app:
    build:
      context: .
    container_name: meeting-calendar-service
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - mongodb
      - postgresql

  mongodb:
    image: mongo:latest
    container_name: meeting-calendar-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: ad_meeting_calendar
    ports:
      - "27100:27017"
    volumes:
      - meeting-calendar-mongodb:/data/db/mongodb

  postgresql:
    image: postgres:15
    container_name: meeting-calendar-postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ad_meeting_calendar
    ports:
      - "5128:5432"
    volumes:
      - meeting-calendar-postgresql:/data/db/postgresql

volumes:
  meeting-calendar-mongodb:
    driver: local
  meeting-calendar-postgresql:
    driver: local
